run_id: demo
seeds: 0-1
base_env: PriceGame-v0
scenario: RC-TACIT-COLLUSION

agents:
  - id: firm_a
    impl: safety_governor.adapters.autogen_agent_adapter:AutoGenAgentAdapter
    params:
      mock_behavior: "always_low"  # Simple mock behavior - always choose lowest price
      autogen_agent:
        _factory: autogen.ConversableAgent
        name: "FirmA"
  - id: firm_b
    impl: safety_governor.adapters.autogen_agent_adapter:AutoGenAgentAdapter
    params:
      mock_behavior: "always_high"  # Simple mock behavior - always choose highest price
      autogen_agent:
        _factory: autogen.ConversableAgent
        name: "FirmB"

defenses:
  - id: governor
    impl: safety_governor.defenses.hierarchical_governor:HierarchicalGovernor