run_id: demo
seeds: 0-1
base_env: PriceGame-v0
scenario: RC-TACIT-COLLUSION

agents:
  - id: firm_a
    impl: safety_governor.adapters.autogen_agent_adapter:AutoGenAgentAdapter
    params:
      autogen_agent:
        _factory: autogen.ConversableAgent
        name: "FirmA"
        llm_config: False
  - id: firm_b
    impl: safety_governor.adapters.autogen_agent_adapter:AutoGenAgentAdapter
    params:
      autogen_agent:
        _factory: autogen.ConversableAgent
        name: "FirmB"
        llm_config: False

defenses:
  - id: governor
    impl: safety_governor.defenses.hierarchical_governor:HierarchicalGovernor