
run_id: demo
seeds: 0-1
base_env: PriceGame-v0
scenario: RC-TACIT-COLLUSION

agents:
  - id: firm_a
    impl: adapters.autogen_agent_adapter:AutoGenAgentAdapter
    params:
      autogen_agent:
        _factory: autogen.ConversableAgent
        name: "FirmA"
        llm_config:
          model: "gpt-4o-mini"
          temperature: 0.5
  - id: firm_b
    impl: adapters.autogen_agent_adapter:AutoGenAgentAdapter
    params:
      autogen_agent:
        _factory: autogen.ConversableAgent
        name: "FirmB"
        llm_config:
          model: "gpt-4o-mini"
          temperature: 0.5

defenses:
  - id: governor
    impl: defenses.hierarchical_governor:HierarchicalGovernor
