# Minimal test configuration - For automated testing only
# NOT for regular use - missing many required fields

run_id: test_minimal
seeds: 0
base_env: PriceGame-v0
scenario: TEST
max_steps: 5

agents:
  - id: test_agent
    impl: safety_governor.adapters.autogen_agent_adapter:AutoGenAgentAdapter
    params:
      name: "TestAgent"
      llm_config:
        provider: "ollama"
        model: "deepseek-r1:1.5b"
        temperature: 0.1
        max_tokens: 50
      system_prompt: "Test agent. Always output valid JSON."
      prompt_template: "price_game"
      game_type: "price_game"
      agent_index: 0
      autogen_agent:
        _factory: autogen.ConversableAgent
        name: "TestAgent"

logging:
  level: ERROR  # Minimal logging for tests