base_env: PriceGame-v0
seeds: 42  # Single seed test

agents:
  - id: firm_a
    impl: adapters.autogen_agent_adapter:AutoGenAgentAdapter
    params:
      autogen_agent:
        _factory: autogen.ConversableAgent
        name: "FirmA"
        llm_config: False

  - id: firm_b 
    impl: adapters.autogen_agent_adapter:AutoGenAgentAdapter
    params:
      autogen_agent:
        _factory: autogen.ConversableAgent
        name: "FirmB"
        llm_config: False

defenses:
  - id: governor
    impl: defenses.hierarchical_governor:HierarchicalGovernor